CREATE TABLE Listing(
	id int NOT NULL AUTO_INCREMENT,
	listing_uuid varchar(36) NOT NULL UNIQUE,
	bidder_uuid varchar(36) NOT NULL UNIQUE,
	seller_uuid varchar(36) NOT NULL UNIQUE,
	description varchar(350) NOT NULL,
	image varchar(250) NOT NULL,
	created datetime DEFAULT NOW() NOT NULL,
	updated datetime DEFAULT NOW() NOT NULL,
	listing_days int NOT NULL,
	currency varchar(10) DEFAULT 'USD' NOT NULL,
	start_price decimal NOT NULL,
	reserve_price decimal NOT NULL,
	num_bids int DEFAULT 0 NOT NULL,
	end_time datetime NOT NULL,
	bid_increment decimal NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (bidder_uuid) REFERENCES Users(acc_uuid),
	FOREIGN KEY (seller_uuid) REFERENCES Users(acc_uuid)
);