CREATE TABLE Listing(
	id int NOT NULL AUTO_INCREMENT,
	listing_uuid varchar(36) NOT NULL UNIQUE,
	seller_uuid varchar(36) NOT NULL,
	cat_id int(11) NOT NULL,
	sub_id int(11) NOT NULL,
	item_name varchar(250) NOT NULL,
	description varchar(350) NOT NULL,
	image varchar(250) NOT NULL,
	created datetime DEFAULT NOW() NOT NULL,
	updated datetime DEFAULT NOW() ON UPDATE NOW() NOT NULL,
	listing_days int NOT NULL,
	currency varchar(10) DEFAULT 'USD' NOT NULL,
	start_price decimal(10,2) NOT NULL,
	reserve_price decimal(10,2),
	num_bids int DEFAULT 0 NOT NULL,
	end_time datetime NOT NULL,
	bid_increment decimal(10,2) NOT NULL,
	is_active int DEFAULT 1 NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (seller_uuid) REFERENCES Users(acc_uuid),
	FOREIGN KEY (cat_id) REFERENCES Category(id),
	FOREIGN KEY (sub_id) REFERENCES SubCategory(id)
);
